---
apiVersion: v1
kind: Namespace
metadata:
  name: smile-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: smile-app
  name: deployment-smile
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-smile
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-smile
    spec:
      containers:
      - image: srivyshnavi01/smileappimage:latest
        imagePullPolicy: Always
        name: app-smile
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: smile-app
  name: service-smile
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-smile
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: smile-app
  name: ingress-smile
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-smile
                port:
                  number: 8000
